### ISSUE TITLE
enforce-crosschain in policy

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/marmalade#105]
### Context (Environment)

Marmalade v2

### Detailed Description

In Marmalade v1 the token-policy interface had a function: `(enforce-crosschain`

In Marmalade v2 this function has been removed. Are there some rationales behind ?

Even if the official ledger doesn't currently support the X-chain transfer, nothing prevents to implement it (in the official ledger or in a fork). Ideally we would need the `(enforce-crosschain` function to be restored to let the NFT issuer define precisely the authorization in a X-chain case (ie source / dest chains, combined with other factors).
  
Remember that an interface is not upgradable in Pact. Thus if a function is missing, we will miss it for years. 
Moreover the cross-chain feature is still present in `poly-fungible-v3` => it makes senses to keep it in `token-policy-v2` as well. 

BTW: 
   - There are still many hints of `(enforce-crosschain` in the current Marmalade v2: Both in code and in doc.
   

### Possible Implementation

Solution 1:
  - Clean all hints of `(enforce-crosschain` from the code if you decide that this feature is not useful anymore
 
 Solution 2: 
   -  Restore `(enforce-crosschain  ` in the policy interface and implement it in each policy with a "do-nothing" function. 
   
   What's your opinion? I can propose a PR.

**Comment by ggobugi27** [comment]
Thanks for pointing this out. We removed  remnants of the `enforce-crosschain` from the interface and plan to create an interface specific to cross-chain poly fungibles in addition to `poly-fungible-v3`, similar to our coin contract, in the next marmalade upgrade.
