### ISSUE TITLE
Open ended sales

### ISSUE THREAD

**Issue by Gh0stts0hg** [kadena-io/marmalade#109]
### Context (Environment)

To have sales where you dont need to specify a withdraw time, and you can withdraw anytime.

### Detailed Description

currently, users have to specify sale time, if its too short, it may not sell, if too long, they cant withdraw.

From UX it makes sense to allow open ended sales (mybe as an optional) 

### Possible Implementation

if timeout = 0 you can withdraw anytime, and sale will always be active ?

**Comment by jermaine150** [comment]
This PR https://github.com/kadena-io/marmalade/pull/119 solves this issue, and will be included in the go-live of marmalade v2.
