### ISSUE TITLE
V2 - Prevent frontrunning of collections creation

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/marmalade#113]
### Context (Environment)

V2

### Detailed Description

It's possible to front-run a collection creation (and squat a collection/name collection-id).
`(collection-policy-v1.create-collection)`

If the creator doesn't take care, it could allow the squatter to take partial control of the collection and add as many NFT he wants in the collection.
Even if it seems currently pointless, this has to be thought from the initial design.

Just remember how it turned out with Kadena accounts before k: and principals. 

And imagine if CryptoPunks announce that they will port their collection to Marmalade !! 

### Possible Implementation

- Add the principal of the guard (and enforce it at creation !) to the collection-id computation
      - This however doesn't protect the collection name itself
      - This prevents further collection guard rotation

- Add a mechanism of Secret / Commitment to securely create a collection

I can propose a PR, but need your opinion and/or discussion before.

**Comment by daplcor** [comment]
The concept of a secret collection creation process both makes sense and adds a level of pain for automation.  Outside of a request/approval process for collections(nobody really wants this), I feel it would be nice to sign my guard to a hashed value that later can be revealed.  Once we register the guard, we can reveal the collection-name etc.  It sounds more complex or may not even be possible, but I agree on the premise we don't want front running or maliciously inserted NFTs.

**Comment by CryptoPascal31** [comment]
The idea I have in my brain is the following:

- The creator submit a `commitment = HASH(collection_name + guard)`. This is stored by the SC. At this point the collection_name is still secret only known by the creator.

After the transaction has been fully confirmed with enough blocks. It's critical for the frontend/user to check this condition. 

- The creator submit a transaction with the following arguments that reveal the collection_name and the guard. The transaction has to be signed by the guard. The SC must check that `commitment = HASH(collection_name + guard)` and that the required number of confirmations has been reached.

With this mechanism, it's impossible to steal the "collection_name". They only way for an attacker is to control enough hash power to censor the 2nd transaction for at least the required number of confirmations. 

This process is painful for automation, but has to be done only one time when registering a new collection.

**Comment by jermaine150** [comment]
Thanks for the feedback @CryptoPascal31 @daplcor, A PR has been created including the operator guard in the collection id and enforcing it in id creation #133
