### ISSUE TITLE
V2 - Prevent  front-running of token creation

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/marmalade#114]
### Context (Environment)

V2

### Detailed Description

Even with `t:` ids, token creation can be front-run.

The `t:` token name generation does only take into account URI and policies list. 
But not the parameters of the policies, which are transmitted in the data section of the transaction.

Thus a squatter could front-run and steal a `t:` token-id by submitting to the ledger a token creation request with the same URI, same list of policies but different policy parameters. 
Especially if the legit creator has chosen to use the `guard-policy`, the squatter could be able to "front-create" the token with its own guards.

In the best case, a bot could prevent any token creation.
In the worst case, if the legit creator doesn't take care, a squatter could take silently control of a token.

### Possible Implementation

For a creator, one possibility (workaround) to secure its tokens creation is to always include a custom policy with a protected `(enforce-init)`. 
But with the current API and doc, I can't see nothing that could encourage the creators to do so.

---

One other possibility, is to add an argument: `creation-guard` to `(ledger.create-token)`:
   - The ledger must enforce that guard
   - And use it for the `t:` token name computation.

This guard doesn't need to be stored. It's just a temporary guard to be sure that nobody isn't able to  steal the `t:` token names.

**Comment by jermaine150** [comment]
Solved by https://github.com/kadena-io/marmalade/pull/142
