### ISSUE TITLE
Transfer to escrow for auction sales

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#116]
### Context (Environment)

I would like to allow users to easily transfer NFT's into an escrow account for securing an auction.

### Detailed Description

I would like a method or override that lets us list an NFT up for auction, but transfers are explicitly denied on the royalty policy unless I'm missing something.  Changing false to true allows me to proceed with testing royalty enabled NFT's for auction.

### Possible Implementation

Add a new hook into the royalty policy that allows NFT's to transfer into an escrow account that is supported by this policy directly.  It requires a positive amount of the coin for it to release.  this should cover most use cases without an over bearing structure.

**Comment by jermaine150** [comment]
Closing this since with the introduction of `sale-contracts` in Marmalade V2 we have a secure solution of putting up NFT's for auction.
