### ISSUE TITLE
[Bug]: V2 - Possible inconsistency of fungible between the royalty-policy and a sale 

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-io/marmalade#127]
### Expected Behavior

...

### Current Behavior

The fungible currency of the royalty-policy in created at init time by the creator:
https://github.com/kadena-io/marmalade/blob/d810478bed01eb4cf145a2e8dfaf15043b638b9e/pact/concrete-policies/royalty-policy/royalty-policy-v1.pact#L56

But when the token is being sold, the seller is allowed to choose another currency when he initiates the sale:
https://github.com/kadena-io/marmalade/blob/d810478bed01eb4cf145a2e8dfaf15043b638b9e/pact/quote-manager/quote-manager.pact#L156

If it choose a different currency than the creator, the sale won't be settled, as it will fail during the royalty-payment. 
https://github.com/kadena-io/marmalade/blob/d810478bed01eb4cf145a2e8dfaf15043b638b9e/pact/concrete-policies/royalty-policy/royalty-policy-v1.pact#L131

And the token may be left locked in a sale `(defcap` that can be finished.  

### Possible Solution

...

### Steps to Reproduce

...

**Comment by ggobugi27** [comment]
The royalty policy does limit the tokens to only be sellable by the specified fungible. We can discuss about possible methods to guarantee the royalty payout

**Comment by CryptoPascal31** [comment]
I may be wrong, I may miss something.
But I don't see such enforcement in the code.

**Comment by CryptoPascal31** [comment]
I've just sen: https://github.com/kadena-io/marmalade/pull/134

That's a possible solution, that definitively prevent a token from being locked in a sale.

But this is a restrictive solution:
   - when a token has been created with the policy-royalty and a given currency, it is locked until the end of times with this currency.

Please, think to this use case:
   - Imagine a token created with a stable coin as payment currency
   - And imagine that later for some reason (remind what happened with Lago cwUSD ) , later, this stable coin is not used anymore, or its fungible contract disabled by the issuer

=> The Marmalade token is not tradable anymore, and lost all its value until end of times....
