### ISSUE TITLE
Selling Fee

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#170]
### Context (Environment)

For marketplaces and custom services that want to build a business model around offering sales/auction/other services, they will at times, want to implement fees.  When an item is hosted on marketplace A, they should be able to offer the item with a built-in fee attached, potentially in the quote itself.  If users want to avoid fees, they can initiate or find a service that might offer more aggressive rates or even free.

### Detailed Description

Please consider adding a field in the quote for marketplace fees that can be executed during the auction end distribution process.

**Comment by jermaine150** [comment]
Closing this in favor of #171
