### ISSUE TITLE
Sales Fee

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#171]
### Context (Environment)

For marketplaces and custom services that want to build a business model around offering paid services, they will at times, want to implement fees.  When an item is listed for sale, it would be helpful to notify the user and introduce a marketplace type fee on sales.  If users want to avoid fees, they can initiate or find a service that might offer more aggressive rates or even free.

### Detailed Description

Implement a fee structure similar to how royalties are combined in the final tx, to introduce a marketplace or private sale fee, which is distributed as part of the continuation that was signed by the buyer.

**Comment by jermaine150** [comment]
Thanks for bringing this up. I see you also created #170. 
We currently have two ways of selling your token, 1 is with a simple quote, incorporated in the policy manager and the other is by extending this process with logic contained in a `sale-contract`. I see you created this issue and #170 to cover these two cases.

However, when implementing this we'll be looking for a generic way that supports both processes, therefore I'll close #171 so  we can continue the discussion overhere. I'll take this up with the team and will update in this thread.

**Comment by jermaine150** [comment]
@daplcor see #175 for a possible implementation of marketplace fees.

**Comment by jermaine150** [comment]
The marketplace fees implementation has been deployed on testnet

**Comment by jermaine150** [comment]
Marketplace fees have now been deployed to mainnet! @daplcor
