### ISSUE TITLE
[Bug]: Auction Contract Row Not Found

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#172]
### Expected Behavior

When I offer up an NFT with the marmalade-sale.conventional-auction it should let me list a token for sale to be auctioned.

### Current Behavior

I am receiving the following error when trying to list an NFT for auction on mainnet.  "with-read: row not found: marmalade-sale.conventional-auction"

### Possible Solution

I believe there is an approved policy list that allows us to trigger this behavior.

### Steps to Reproduce

Run the sale process for any NFT with "sale-type": "marmalade-sale.conventional-auction"

**Comment by jermaine150** [comment]
conventional-auction isn't initialized on mainnet yet because of the changes to sale-interface (#166). These changes are still on testnet. When they will be deployed on mainnet I will report back here.

**Comment by jermaine150** [comment]
@daplcor the conventional-auction is deployed on mainnet, and added to the whitelist. That solves this issue.
