### ISSUE TITLE
Confused by some parts of the KIP

### ISSUE THREAD

**Issue by severian1778** [kadena-io/marmalade#61]
It seems that the Haber Content Manifest is there in the kip w.r.t URIhash but there is no NodeHash Algorithm or hash linking with the time stamp in the code base.  

Can the team point us to where this content is or inform us if it's yet to be pushed in the next release?   Is there a Beta version we can play with?

**Comment by sirlensalot** [comment]
It is possible to link tokens and perform other iterative hashing using the `manifest` as well as `chain-data` to get the latest timestamp. Content integrity a la Haber is still in the design phase however and is not part of the current beta.

**Comment by severian1778** [comment]
Thank you @sirlensalot that is very helpful and clears things up.   It was slightly confusing to see the CIS suggested in the main Github page via the link to Haber's paper but then we couldn't find the Merkle tree rollup in the code.   KDAbet is very excited for that functionality and we will redouble our effort to perform the iterative hashing with current tools available.
