### ISSUE TITLE
Excessive Gas collection-policy-v1.pact

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#70]
When running through the collection builder, I am running into issues with gas usage.  To replicate issue, I built a repl that simulates 10,000 NFT's and requires between 175,000-180,000.  Lookups against the NFT table are small, but initial creation causes issues with high gas requirements.  For reference, 2,000 NFT collection cost ~35,000 gas on average.

I'm going to test various data structures to see if I can reduce the gas cost, but needed to note this issue so others can get eyes on it.  
  (defschema collection
    id:string
    collection-size:integer
    collection-hash:string
    tokens:[string]
    operator-guard:guard
  )

**Comment by jermaine150** [comment]
The collection schema has been updated, the `tokens` argument has been removed from the collection schema.
