### ISSUE TITLE
Collection Enforcement

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#71]
https://github.com/kadena-io/marmalade/blob/8cdb0d7c78520245d3cc2e7614cfcaf044be4ff0/pact/concrete-policies/collection-policy/collection-policy-v1.pact#LL69C13-L69C13

When enforcing collections we validate token hash list is expected to match the provided collection-hash and this works great.  Please consider the following code to also enforce(= collection-size token-list-size).  

  (defun init-collection:bool
    (collection-id:string
      collection-size:integer
      collection-hash:string
      tokens:[string]
      operator-guard:guard
      )
      (with-capability (INIT_COLLECTION collection-id collection-size collection-hash)
        (enforce (= collection-hash (hash tokens)) "Token manifests don't match" )
        (let ((actual-size (length tokens)))
          (enforce (= collection-size actual-size) (format "Token length doesn't match list. Expected: {}, Actual: {}" [collection-size actual-size]))
        )
        (insert collections collection-id {
          "id": collection-id
          ,"collection-size": collection-size
          ,"collection-hash": collection-hash
          ,"tokens": tokens
          ,"operator-guard": operator-guard
        }
        )
      )
      true
  )

**Comment by jermaine150** [comment]
Thanks for the feedback. Do note that the v2 branch is still under development so keep in mind that breaking changes will occur.
The collection-hash and tokens list have been omitted from this function (which has been renamed to `create-collection`), therefore this comment isn't applicable anymore.
