### ISSUE TITLE
Operator cap issue

### ISSUE THREAD

**Issue by daplcor** [kadena-io/marmalade#73]
https://github.com/kadena-io/marmalade/blob/8cdb0d7c78520245d3cc2e7614cfcaf044be4ff0/pact/concrete-policies/collection-policy/collection-policy-v1.pact#LL89C12-L89C12

This cap should be rescoped to include collection-id.  In the defcap it's using collection-id not token-id and this causes failure.  

Working code snip here.
    (with-capability (OPERATOR collection-id)

**Comment by jermaine150** [comment]
Thanks, fixed in this [commit](https://github.com/kadena-io/marmalade/commit/d95bc622a3086c39f36452553a02cb29577fd7f7#diff-19f3a95795d3f865e83223ad1b0194d91453c6444ec2b419001c53294191e196)
